import { useArticle } from "@/hooks/use-articles";
import { useRoute, Link } from "wouter";
import { Loader2, ArrowLeft, Share2, Printer, Bookmark } from "lucide-react";
import { Button } from "@/components/ui/button";
import { format } from "date-fns";
import { Separator } from "@/components/ui/separator";

export default function ArticleView() {
  const [, params] = useRoute("/article/:id");
  const idOrSlug = params?.id || "";
  
  // Try to parse as number, otherwise use as slug
  const parsedId = parseInt(idOrSlug);
  const identifier = !isNaN(parsedId) && parsedId.toString() === idOrSlug ? parsedId : idOrSlug;
  
  const { data: article, isLoading, error } = useArticle(identifier);

  if (isLoading) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center space-y-4">
        <Loader2 className="h-12 w-12 animate-spin text-primary" />
      </div>
    );
  }

  if (error || !article) {
    return (
      <div className="min-h-[50vh] flex flex-col items-center justify-center text-center">
        <h2 className="font-display text-3xl font-bold mb-4">Article Not Found</h2>
        <p className="text-muted-foreground mb-8">This story may have been archived or removed.</p>
        <Link href="/">
          <Button variant="outline">Back to Headlines</Button>
        </Link>
      </div>
    );
  }

  return (
    <article className="max-w-4xl mx-auto pt-8 animate-in fade-in duration-500">
      {/* Navigation & Meta */}
      <div className="flex justify-between items-center mb-8">
        <Link href="/">
          <Button variant="ghost" className="pl-0 hover:bg-transparent hover:text-accent font-sans uppercase font-bold tracking-widest text-xs">
            <ArrowLeft className="mr-2 h-4 w-4" />
            Back to Feed
          </Button>
        </Link>
        <div className="flex gap-2">
          <Button variant="ghost" size="icon" className="text-muted-foreground hover:text-primary">
            <Share2 className="h-4 w-4" />
          </Button>
          <Button variant="ghost" size="icon" className="text-muted-foreground hover:text-primary">
            <Bookmark className="h-4 w-4" />
          </Button>
          <Button variant="ghost" size="icon" className="text-muted-foreground hover:text-primary">
            <Printer className="h-4 w-4" />
          </Button>
        </div>
      </div>

      {/* Header */}
      <header className="mb-12 text-center">
        <Link href={`/category/${encodeURIComponent(article.category)}`}>
          <span className="inline-block bg-accent/10 text-accent font-bold px-3 py-1 text-xs uppercase tracking-widest mb-6 hover:bg-accent/20 transition-colors cursor-pointer">
            {article.category}
          </span>
        </Link>
        
        <h1 className="font-display font-black text-4xl md:text-5xl lg:text-6xl leading-[1.1] mb-8 text-primary">
          {article.title}
        </h1>

        <div className="flex items-center justify-center gap-4 text-sm font-sans uppercase tracking-widest text-muted-foreground border-y border-border py-4">
          <span>By AI Editor</span>
          <span className="w-1 h-1 bg-muted-foreground rounded-full"></span>
          <span>{article.createdAt ? format(new Date(article.createdAt), "MMMM d, yyyy") : "Recently"}</span>
          <span className="w-1 h-1 bg-muted-foreground rounded-full"></span>
          <span>5 Min Read</span>
        </div>
      </header>

      {/* Hero Image */}
      {article.imageUrl && (
        <div className="mb-12 shadow-2xl overflow-hidden bg-secondary">
          <img 
            src={article.imageUrl} 
            alt={article.title}
            className="w-full h-auto object-cover max-h-[600px]"
          />
          <div className="bg-secondary/50 p-3 text-right">
            <span className="text-[10px] font-sans uppercase tracking-widest text-muted-foreground">Image Generated by AI</span>
          </div>
        </div>
      )}

      {/* Content */}
      <div className="prose prose-lg md:prose-xl prose-stone mx-auto font-serif text-foreground/90 leading-loose">
        <p className="lead font-bold text-2xl mb-8 not-italic text-foreground/80 leading-relaxed border-l-4 border-accent pl-6">
          {article.summary}
        </p>

        {/* We're splitting content by newlines for basic formatting since it's text */}
        <div className="space-y-6">
          {article.content.split('\n').map((paragraph, idx) => {
            if (!paragraph.trim()) return null;
            return (
              <p key={idx} className={idx === 0 ? "drop-cap" : ""}>
                {paragraph}
              </p>
            );
          })}
        </div>
        
        <div className="mt-12 p-6 bg-secondary rounded-none border-l-4 border-primary">
          <h4 className="font-sans font-bold uppercase text-xs tracking-widest mb-2 text-primary">Source Reference</h4>
          <p className="text-sm text-muted-foreground italic font-serif truncate">
            {article.originalSource}
          </p>
        </div>
      </div>

      <div className="article-divider mt-20" />

      {/* Read Next Logic would go here */}
    </article>
  );
}
